version: "3.4"
services:
  heif-3d:
    restart: unless-stopped
    build:
      context: ../
    labels:
      # Traefik configuration, Hostname needs to be changed
      - traefik.http.routers.heif-3d-http.rule=Host(`heif-3d.dakantz.at`)
      - traefik.http.routers.heif-3d-http.entrypoints=http
      - traefik.http.routers.heif-3d-http.middlewares=redirect
      - traefik.http.routers.heif-3d-https.rule=Host(`heif-3d.dakantz.at`)
      - traefik.http.routers.heif-3d-https.entrypoints=https
      - traefik.http.routers.heif-3d-https.tls=true
      - traefik.http.routers.heif-3d-https.tls.certresolver=letsencrypt
      - traefik.http.services.heif-3d.loadbalancer.server.port=80
      - traefik.http.middlewares.redirect.redirectscheme.scheme=https
    networks:
      - web
      - internal
networks:
  web:
    external: true
  internal:
    external: false